### ISSUE TITLE
Test 23.04/24.04

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#112]
- [ ] Testplan @vanessabay @JP-Kaiser @PeterHolland-Moritz 
- [ ] Testcode
- [ ] Testfälle 
-- [ ] Reader TESTEN @JP-Kaiser @PeterHolland-Moritz 

- [ ] Testdaten 
- [ ] Testprotokolle

**Comment by YeGaSoft** [comment]
Veralteter Issue, von dem es bereits eine neue Version gibt.
