### ISSUE TITLE
OnValidSubmit funktioniert nicht

### ISSUE THREAD

**Issue by OliverWuensche** [jonashoelzel/ZEISS_Verwaltungssystem#119]
Die erfolgreiche Validierung bei korrekter Eingabe funktioniert im Workflow bei folgendem nicht:

- Titel (WorkingTitle)
- eventuell Titel auch PublicationTitle
(noch nicht Implementiert) 

Lediglich OnInvalidSubmit wird ausgelöst.

Leeres Textfeld --> Fehlermeldung wird ausgegeben; Weiter-Button funktioniert wie erwartet nicht
Gefülltes Textfeld (Bsp. Dokument XYZ) --> Keine Fehlermeldung wie zu erwarten; Weiter-Button funktioniert nicht, sollte aber

**Comment by YeGaSoft** [comment]
Der Bug sollte gefixt sein.
