### ISSUE TITLE
Neue Datenspeicherstuktur für die Excel

### ISSUE THREAD

**Issue by jonashoelzel** [jonashoelzel/ZEISS_Verwaltungssystem#134]
Umsetzung der Datenspeicherstuktur im DataLayer

**Comment by YeGaSoft** [comment]
@jonashoelzel, könnest du bitte den nötigen Code im DataSet erstellen?
Ich würde mich dann darum kümmern, dass die Daten in die Excel eingetragen werden.
Sozusagen nutzt du die aktuelle Insert-Funktion, um die Einträge einzufügen und ich würde dann den Code zum Auslesen bereitstellen, den du dann später nutzen kannst, um die DataSets zu generieren.

**Comment by YeGaSoft** [comment]
Die Struktur wurde bereits implementiert, bzw. befindet sich aktiv in der Entwicklung.
