### ISSUE TITLE
Seitenübersicht nach dem Hinzufügen von Informationen

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#142]
Als Nutzer möchte ich nach dem Eingeben von Informationen die Möglichkeit haben, alle Informationen übersichtlich einsehen zu können, um dann einen Fachbeitrag so hinzuzufügen oder noch Veränderungen vornehmen zu können.

- Nutzer muss nach dem Eingeben aller Informationen nachdem er "Veröffentlichung hinzufügen" gedrückt hat, eine übersichtliche Ansicht aller eingegebenen Daten erhalten (in Form von PopUp)
-> diese muss er mit "Hinzufügen" noch bestätigen, kann aber dort auch "Abbrechen" klicken, der Nutzer gelangt wieder zurück zu seinen eingegebenen Daten
- ähnlich einer Bestellübersicht bei z.B. Amazon

**Comment by YeGaSoft** [comment]
Duplikat.
Siehe #196 für eine genauere Beschreibung.
