### ISSUE TITLE
Veröffentlichungsdaten mithilfe von Suchtext durchsuchen

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#149]
Als Nutzer möchte ich die Liste meiner Beiträge mithilfe von einer Stichwortsuche durchsuchen, damit ich stichwortbezogen die Titel durchsuchen kann.

**Akzeptanzkriterien:**
Funktion:
- Nutzer kann beliebiges Wort in die Suchleiste eingeben und mithilfe der Lupe die Suche starten
- Titel und Namen des Autors werden nach Suchtext durchsucht
- Ergebnisse werden dem Nutzer in der Liste (wie Landing Page) angezeigt
- durch Klick auf das Kreuz in der rechten oberen Ecke wird die Suche beendet

Layout:
- die Suchleiste ist sehr gut für den Nutzer sichtbar
- Suchleiste befindet sich unter dem Zeiss-Logo mittig und groß auf der Landing Page

**Beispiel "Stichwortsuche":**

![image](https://user-images.githubusercontent.com/73165146/116550204-bfe7e900-a8f6-11eb-8bc7-9155e8c69b61.png)

![image](https://user-images.githubusercontent.com/73165146/116550223-c7a78d80-a8f6-11eb-8c79-469d0bf86c64.png)

![image](https://user-images.githubusercontent.com/73165146/116550237-cd9d6e80-a8f6-11eb-9447-1dadeaddf39c.png)

![image](https://user-images.githubusercontent.com/73165146/116550257-d55d1300-a8f6-11eb-838c-fe1b18ab5a95.png)

![image](https://user-images.githubusercontent.com/73165146/116550276-dd1cb780-a8f6-11eb-9167-fb9301986598.png)

**Comment by YeGaSoft** [comment]
Task Done und wird extra archiviert.
