### ISSUE TITLE
must have MVP festlegen

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#16]

**Comment by PeterHolland-Moritz** [comment]
Prototyp:
neuer Eintrag (UI mindestens Menus, keine Bash) :
	-über Formular Daten erfassen (Alle Felder)
	-Vorauswahl Dropdown-Menu (Autoren,Art,Medium,Status...)
	-Formatierung Input (Nachname - Vorname,Datum)	

-Statistiken erfassen (aus Datensätzen erstellen)
-Excel einlesen und verwenden bei Vorschlägen/Statistiken (Autoren)
??? -Suchen (Autor/Titel -> Artikel/Eintrag linken in geeigeter Form)


Später (nicht im Protoyp):
-Nutzer / Logins 
-Cross-eintrag in Exccel Liste / Portbar nach Excel
-Benachichtugung (Gruppenleiter, Workflow)
-Einbinden Artikel -> .NET einbinden
-Offline Modus
