### ISSUE TITLE
Landing Page verändern

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#178]
Anfangsseite soll entfernt werden und man soll direkt auf der Landing Page starten:

![image](https://user-images.githubusercontent.com/73165146/118006076-3d761500-b34b-11eb-9526-4bd1945c2234.png)

Veröffentlichung hinzufügen erfolgt über das kleine blaue Plus in der rechten Ecke.

**Comment by YeGaSoft** [comment]
Erledigt.
