### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by OliverWuensche** [jonashoelzel/ZEISS_Verwaltungssystem#184]
- [x] Button "optionale Angaben" mit "Veröffentlichung hinzufügen" tauschen
- [x] "optionale Angaben" Button kleiner
- [x] Button rechts unten "Call to Action" -> Rest sekundäre Buttons
- [x] Spaltenheader Sortierungssymbole fixen
- [x] alternierende Spalten-Hintergründen farblich anpassen (table-hover)
- [x] Buttons generell kleiner
- [x] Aktionsbuttons (Bearbeiten, Löschen) nur mit Icons und farblich anpassen
- [x] AddTitle-Panel: "Dokument" <-> ""Titelname" anpassen

**Comment by YeGaSoft** [comment]
Erledigt.
