### ISSUE TITLE
(minor Bugs) Testcase 2 Datumsauswahl Veröffentlichung

### ISSUE THREAD

**Issue by PeterHolland-Moritz** [jonashoelzel/ZEISS_Verwaltungssystem#186]
- [x]  Jahresangaben unter 100 crashen Programm
- [x] TT.MM.JJJJ wird akzeptiert und aktuelles Datum automatisch ausgefüllt (clearing von Datum per [x])

Mitschriften: Teams>Testing>Test_Skript_2_Datumsauswahl_Veröffentlichung

**Comment by YeGaSoft** [comment]
fixed
