### ISSUE TITLE
START PAGE: Eine Excel-Datei auswählen und hinterlegen

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#190]
**Hinweis:**
Als Nutzer möchte ich den Datei-Pfad einer Excelliste auswählen damit das Programm Zugriff auf die ausgewählte Datei erhält und somit das Programm im vollem Umfang nutzbar ist. 

**START-PAGE**
mit #202 

**Akzeptanzkriterien:**

_Funktion:_

- Aufruf Datei-Explorer 
- bestätigte Auswahl: 
1. Einlesen des Dateipfades 
2. Zugriff auf Excel-Datei 
3. Lesen der Excel-Datei-> Import der Excel-Datei 
4. Einpflegen der Exceldatei als Datenbank 

_Layout:_

- START-PAGE: 1. Button rechts "Pfad auswählen"

START: Aktionsaufruf mit Button - Aufruf lokaler Datei-Explorer (Windows) 

1. "Wählen" (WINDOWS: Datei-Explorer) 
→ switch Page -> MAIN-PAGE: Datensätze werden formgerecht dargestellt 
ENDE User Story

2. "Abbrechen" (WINDOWS: Datei-Explorer)  
→ Abbruch Datei-Explorer - START-PAGE
ENDE User Story

**Comment by YeGaSoft** [comment]
Implementiert.
