### ISSUE TITLE
Löschen eines bestehenden Autors im System - Prio 2.1

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#191]
Diese Story setzt die Bearbeitung der Story #218 voraus.

**Hinweis:**
Als Nutzer möchte ich einen bereits hinzugefügten Autor entfernen, damit dieser danach nicht mehr gelistet ist.

**Akzeptanzkriterien:**
Funktion:
- im Programm bestehender Autor wird komplett entfernt

Layout:
- Tab: Autoren
- Übersicht der Autoren
- Aktionsspalte: Stift und Kreuz (siehe Main Page --> Veröffentlichungen)
- Auswahl Kreuz: 
- IF Autor besteht in mindestens einer Veröffentlichung --> nicht entfernbar
- ELSE: lösche Autor
- Zeile wird entfernt, andere Autoren rücken nach

**Comment by YeGaSoft** [comment]
Task Done.
