### ISSUE TITLE
Bedienungshilfe beim Löschen einer Veröffentlichung

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#201]
**Hinweis:**
Als Nutzer möchte ich gezwungen werden die Aktion - Veröffentlichung löschen - zu betätigen damit dem unerwünschten Löschen von Veröffentlichungen vorgebeugt wird. 

Diese Story setzt die Realisierung der UserStory #54 voraus.

**Akzeptanzkriterien:**
Funktion:
- erzwingt Benutzerinteraktion
- Aktion #54 wird ausgeführt oder abgebrochen 

Layout:
- Programmaufruf mittels Aufruf Aktion #54 - eine Veröffentlichung löschen
- PopUp- Interaktion "Eintrag wirklich löschen?"
Button-links: "Löschen" -> Aktion #54 wird ausgeführt -> Pop-Up-Info
Button-rechts: "Abbrechen" -> Ende Bedienungshilfe -> Main-Page
- Pop-Up-Info "Eintrag gelöscht" - _Aufruf nach Button "Löschen"_
Button: "Okey" -> Main-Page

![image](https://user-images.githubusercontent.com/73165146/118952278-18d9f880-b95c-11eb-9c56-ab1ebf54b2ab.png)

![image](https://user-images.githubusercontent.com/73165146/118952311-20010680-b95c-11eb-9202-81b6682337a0.png)

**Comment by YeGaSoft** [comment]
Fertig und archiviert.
