### ISSUE TITLE
START PAGE: Eine neue Excel-Datei erstellen und hinterlegen

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#202]
**Hinweis:**
Als Nutzer möchte ich auch ohne Zugriff auf die vorhandene Exceldatei der Veröffentlichungen, Einträge formgerecht erfassen.

**START-PAGE**
mit #190 

**Akzeptanzkriterien:**

_Funktion:_ 

- Aufruf Datei-Explorer
- Zugriff auf Speicherort 
- bestätigte Auswahl: 
1. Einlesen des Dateipfades 
2. Zugriff auf Excel-Datei 
3. Lesen der Excel-Datei-> Import der Excel-Datei 
4. Hinterlegung der Exceldatei als Datenbank 

_Layout:_

- START-PAGE - 1. Button links "Neue Excelliste erstellen"

- START: Aktionsaufruf mit Button - Aufruf lokaler Datei-Explorer (Windows) 

1. "Wählen" (WINDOWS: Datei-Explorer) - nach Speichern neuer Excel-Datei (WINDOWS: Datei-Explorer)
→ switch Page -> MAIN-PAGE 
ENDE User Story

2. "Abbrechen" (WINDOWS: Datei-Explorer)
→ Abbruch Datei-Explorer - START-PAGE
ENDE User Story

**Comment by YeGaSoft** [comment]
Fertig.
