### ISSUE TITLE
Bezeichnungsänderungen in UI

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#217]
- [x]  Bei Hinzufügung/ Änderung heißt das Attribut "Titelname". Dies soll zu "Titel der Veröffentlichung" geändert werden.
- [x] "Geschäftsbereich" soll "Geschäftsbereich von ZEISS" werden
- [x] "Autor" soll zu "Autor der Veröffentlichung" werden

**Comment by YeGaSoft** [comment]
Erledigt.
