### ISSUE TITLE
I want to be forced to input mandatory Info

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#36]
As a User, I want to i want to be forced to input mandatory Info so that I dont forget mandatory Input. 

Epic #35

**Comment by Pauljoksch** [comment]
Mandatory: 
- Autoren Name (Vorname, Nachname)
- titel
- Datum 
- Bereich
- Art der Veröffentlichung

**Comment by YeGaSoft** [comment]
Merged into "Editing and managing UI input".
