### ISSUE TITLE
Be able to add tags to a publication

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#37]
As a User, I want to be able to add Addiotional Info so that i can describe further and sort better later on.

Epic #35

**Comment by YeGaSoft** [comment]
Tasks:


Task 1 (UI): Create a menu where an admin can add/remove/rename tags that can be selected.

Task 2 (IL): Save/Update the tags in a Separated Worksheet.

Task 3 (IL): Update the tags column values in the Main Worksheet (saved as CSV).

Task 4 (IL): Load tags from Separated Worksheet.

Task 5 (UI): Create checkboxes for all divisions in the UI where the user can select multiple tags.

Task 6 (IL): Save the tags in Main Worksheet as CSV.

Task 7 (BL): Implement search and filter methods to search or filter tags.

**Comment by YeGaSoft** [comment]
Merged into "Add information".
