### ISSUE TITLE
Add additional Description to a publication

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#38]
As a User, I want to add additional Description so that i can describe further.

Epic #35

**Comment by YeGaSoft** [comment]
Tasks:


Task 1 (UI): Create input field to enter description.

Task 2 (IL): Save/Update description of entry in Main Worksheet.

**Comment by YeGaSoft** [comment]
Merged into "Add information".
