### ISSUE TITLE
Review Usecase 1

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#4]
[https://github.com/jonashoelzel/ZEISS_Verwaltungssystem/blob/main/docs/requirements/use_case_01.inc.adoc#verpflichtende-angaben-zum-beitrag](url) 

ein wenig ein Test issue aber auch die Frage, warum Medium der Veröffentlichung nicht verpflichtend

**Comment by YeGaSoft** [comment]
Die Use Cases wurden basierend auf dem Kundengespräch angepasst.
