### ISSUE TITLE
Add a new division to the List

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#41]
As a User, I want to add a new division to the List so that can add better fitting or new divisions.

ID: US007
Epic: #35

**Comment by YeGaSoft** [comment]
Tasks:

Task 1 (UI): Create a menu where an admin can add/remove/rename divisions that can be selected.

Task 2 (IL): Save/Update the divisions in a Separated Worksheet.

Task 3 (IL): Update the divisions column values in the Main Worksheet (saved as CSV).

Task 4 (IL): Load divisions from Separated Worksheet.

Task 5 (UI): Create checkboxes for all divisions in the UI where the user can select multiple divisions.

Task 6 (IL): Save the divisions in Main Worksheet as CSV.

Task 7 (BL): Implement search and filter methods to search or filter divisions.

**Comment by YeGaSoft** [comment]
Merged into "Add information".
