### ISSUE TITLE
Pflichteingaben einer Veröffentlichung ändern (M) - Prio 1

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#52]
**Hinweis:**
Als Nutzer möchte ich alle Eigenschaften eines Eintrags bearbeiten können, sodass dieser dann unter den veränderten Attributen gelistet ist.

**Akzeptanzkriterien:**
Funktion:
- jedes Feld bearbeitbar, **AUSNAHME:**
1. Felder nicht leer 
2. Felder maximal 200 Zeichen
- Bei Bestätigung: Vollständige Überschreibung der vorherigen Daten

Layout:
- Start der Aktion: **Stift in der Aktion-Spalte**
- Workflow Bearbeiten-Modus = Workflow Hinzufügen-Modus, **AUSNAHME:** 
1. Überschrift "Veröffentlichung bearbeiten" 
2. vorhandene Daten sind bereits eingetragen
- Bestätigung: "Änderungen aktualisieren" →  Bestätigungs-PopUp 
- Abbruch der Aktion: Button "Abbrechen"

![image](https://user-images.githubusercontent.com/73165146/118949268-56895200-b959-11eb-887a-1e6e116a4bfc.png)

![image](https://user-images.githubusercontent.com/73165146/118949302-5db06000-b959-11eb-857a-e1ce169e30f8.png)

![image](https://user-images.githubusercontent.com/73165146/118949419-80427900-b959-11eb-94c0-603100d26fbe.png)

![image](https://user-images.githubusercontent.com/73165146/118949447-89334a80-b959-11eb-8123-40217dba5a03.png)

![image](https://user-images.githubusercontent.com/73165146/118949506-994b2a00-b959-11eb-821a-0634180c13f1.png)

**Comment by YeGaSoft** [comment]
Merged into "Editing and managing UI input".

**Comment by YeGaSoft** [comment]
Task Done und wird extra archiviert.
