### ISSUE TITLE
Eine Veröffentlichung löschen (S) - Prio 1

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#54]
**Hinweis:**
Als Nutzer möchte ich einen bestehenden Einträge löschen können, sodass dieser dann nicht mehr im Verzeichnis gelistet ist.

**Akzeptanzkriterien:**
Funktion:
- Löschen: gesamter Eintrag aus Liste löschen
- vom Löschvorgang ausgenommen: mit Eintrag hinzugefügte/r ... 
1. Autor
2. Geschäftsbereich
3. Veröffentlichungsart
4. Verlag

Layout:
- Aktion auf Main Page
- Ausführen der Aktion: Löschen-Symbol (Mülleimer oder Kreuz) in der letzten Spalte (s.u.)
- Zeile des Beitrags verschwindet, Beiträge darunter verschiebt es nach oben

![image](https://user-images.githubusercontent.com/73165146/118952244-124b8100-b95c-11eb-891b-77e7817e4a6b.png)

**Comment by YeGaSoft** [comment]
Task Done und wird extra archiviert.
