### ISSUE TITLE
WORKFLOW: Eine Veröffentlichung hinzufügen

### ISSUE THREAD

**Issue by Pauljoksch** [jonashoelzel/ZEISS_Verwaltungssystem#72]
Als  Nutzer möchte ich aufgefordert werden, bei einer Hinzufügung bestimmte Pflichteingaben einzugeben, sodass ich keine Angaben vergesse. 

Pflichtfelder: 
1. Titelname
2. Autor
3. Geschäftsbereich
4. Datum der Veröffentlichung 
5. Art der Veröffentlichung 

**Akzeptanzkriterien:**
Funktion:
- Einpflegen einer Veröffentlichung in Exceldatei
- Eingabeaufforderung der Pflichtfelder
- Veröffentlichung wird nicht hinzugefügt:
1. freie Pflichtfelder 
2. Formatvorgabe nicht erfüllt 
- Formatvorgabe der Eingabeaufforderung: 
1. Titel - 200 Zeichen - String 
2. Autor - 200 Zeichen - String
3. Geschäftsbereich - 200 Zeichen - String
4. Datum der Veröffentlichung - DD/MM/YYYY - YYYY =< 1900 - Date 
5. Art der Veröffentlichung - 200 Zeichen - String 

Layout: 
- Start: "+" in rechter unterer Ecke der Start Page
- Workflow durch einzelne Angaben
- Pfeilnavigation: VOR und ZURÜCK
- Ende der Aktion: "Veröffentlichung hinzufügen"
- Name des Autors: Vorname + Nachname 

**Beispiel "Beitrag hinzufügen:**

![image](https://user-images.githubusercontent.com/73165146/116560939-21fa1b80-a902-11eb-9503-7530ddae60a5.png)

![image](https://user-images.githubusercontent.com/73165146/116560967-2a525680-a902-11eb-9765-0c73117dd2fb.png)

![image](https://user-images.githubusercontent.com/73165146/116561009-31796480-a902-11eb-8f66-578c37aec648.png)

![image](https://user-images.githubusercontent.com/73165146/116561052-3b9b6300-a902-11eb-9ace-3d6560bb2553.png)

![image](https://user-images.githubusercontent.com/73165146/116561076-435b0780-a902-11eb-98df-19a7e651db52.png)

![image](https://user-images.githubusercontent.com/73165146/116561111-4a821580-a902-11eb-84d7-d73a1e48da49.png)

![image](https://user-images.githubusercontent.com/73165146/116561142-52da5080-a902-11eb-8f01-dc6d61f32a6b.png)

![image](https://user-images.githubusercontent.com/73165146/116561160-5a015e80-a902-11eb-828e-e487d78c356b.png)

![image](https://user-images.githubusercontent.com/73165146/116561186-61286c80-a902-11eb-849e-bb56d9171645.png)

![image](https://user-images.githubusercontent.com/73165146/116561216-684f7a80-a902-11eb-93b1-a4b39f05c887.png)

![image](https://user-images.githubusercontent.com/73165146/116561240-700f1f00-a902-11eb-9e3c-b2c12f041443.png)

![image](https://user-images.githubusercontent.com/73165146/116561281-769d9680-a902-11eb-84ed-8d2ce0081534.png)

![image](https://user-images.githubusercontent.com/73165146/116561308-7c937780-a902-11eb-9889-82f126e96a6a.png)

![image](https://user-images.githubusercontent.com/73165146/116561334-8321ef00-a902-11eb-949f-c5e7b78ddea1.png)

**Comment by YeGaSoft** [comment]
Workflow ist teilweise veraltet und wurde in ähnlicher Weise bereits implementiert.
