### ISSUE TITLE
Iterationsplan in Dokument übetragen + NEUES Dokument erstellen

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#91]
Neue Tabelle beginnen, in diese werden alle Issues aufgenommen und deren Stand dokumentiert
- inklusive geschätzter Arbeitsaufwand
- wird ab jetzt immer so gemacht

**Comment by YeGaSoft** [comment]
Alter Issue. Iterationspläne hatten jeweils eigene Issue.
