### ISSUE TITLE
Iterationsplan für Iteration 5 

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#92]
- Was wollen wir am Ende der Iteration haben?
- Was haben wir aktuell?
- Wie gelangen wir dahin?

Dazu Information zur Construction Phase nutzen.

**Comment by YeGaSoft** [comment]
Iteration 5 wurde bereits abgeschlossen. Offene Aufgaben aus Iteration 5 haben eigene Issueses.
