### ISSUE TITLE
Anforderungen überarbeiten

### ISSUE THREAD

**Issue by ninapu** [jonashoelzel/ZEISS_Verwaltungssystem#96]
- Anforderungen aus SE 1 spezifizieren und erweitern/berichtigen

- [x] Use cases @OliverWuensche @ninapu
- [x] Begründung der Entscheidungen @jonashoelzel 
- [x] Systemweite funktionale Anforderungen: Authentifizierung, Export Excel raus nehmen @YeGaSoft 
- [x] Architekturnotebook @jonashoelzel 
- [x] TestCases überarbeiten @JP-Kaiser @PeterHolland-Moritz 
- [x] Domainmodell @vanessabay 
- [x] Benutzerumgebung überarbeiten @OliverWuensche 
- [x] Bedarfe und Hauptfunktionen überarbeiten
- [x] Glossar erweitern/überarbeiten @OliverWuensche

**Comment by YeGaSoft** [comment]
Alter Issue. Mittlerweile ist alles fertig.
